sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 396396
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: sky-take-out-hyb
  redis:
    host: 192.168.164.128
    port: 6379
    password: 396396
    database: 0
  wechat:
    appid: wxfd61df5c19846ad1
    secret: 9ef0b2e1b0f83aae1ba1c4fea9515c1f
